on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Run:
    name: ${{ matrix.platform }} Python ${{ matrix.python-version }} Run
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-13, windows-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Init Environment
        run: make init
      - name: Lint
        run: make flake8
      - name: Test
        run: make test
      - name: Package Publish
        if: startsWith(matrix.platform, 'ubuntu') && matrix.python-version == '3.9' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        run:
          make publish
